name: skrrskrr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.0

dependencies:
  font_awesome_flutter: ^9.2.0
  flutter_svg: ^0.22.0
  audio_waveforms: ^1.0.4
  flutter_fft: ^1.0.2+6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  file_picker: ^5.0.0
  responsive_sizer: ^3.3.1
  go_router: ^13.0.1
  audioplayers: ^6.1.0
  firebase_core: ^3.6.0  # firebase_core의 요구 버전으로 변경
  firebase_auth: ^5.3.1   # firebase_auth의 최신 버전
  google_sign_in: ^6.1.0
  fluttertoast: ^8.2.8
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.11
  image_picker: ^1.0.4
  image_cropper: ^8.0.2
  flutter_local_notifications: ^9.0.0
  permission_handler: ^10.0.0
  cached_network_image: ^3.2.0
  flutter_dotenv: ^5.0.2
  flutter_secure_storage : ^9.2.4
  flutter:
    sdk: flutter
  firebase_messaging: ^15.1.5



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
    - env/

